feature: added auth logic for admin user and basic signup logic.
ValKurta/PhotoShare pull request #2
Opened 2024-10-06 13:21 UTC by iamleeon

2024-10-06 17:52 UTC, ValKurta requested changes

2024-10-06 17:52 UTC, ValKurta commented on src/database/models.py
True як значення за замовчуванням для is_active

2024-10-06 17:52 UTC, ValKurta commented on src/database/models.py
> +    username = Column(String(50), nullable=False, index=True)
Може ще це бути як unique key?

2024-10-06 17:52 UTC, ValKurta commented on src/routes/auth.py
> +        detail="User has been successfully created"
можна додати який саме user був доданий в detail

2024-10-06 17:52 UTC, ValKurta commented on src/routes/__pycache__/auth.cpython-312.pyc
цій файл непотрібен на git - автоматично сгенерований байт-файл. треба додати pycache/ в gitignore

2024-10-06 17:52 UTC, ValKurta commented on src/schemas.py
в pydentic V2 orm_mode замінили на from_attributes=True - буде warning при запускую

2024-10-06 17:52 UTC, ValKurta commented on src/routes/__pycache__/auth.cpython-312.pyc
не потрібен

2024-10-06 17:52 UTC, ValKurta commented on src/services/__pycache__/auth.cpython-312.pyc
не потрібен в гіте

2024-10-06 17:52 UTC, ValKurta commented on src/services/__pycache__/auth.cpython-312.pyc
не треба додавати в git

2024-10-06 17:52 UTC, ValKurta commented on src/services/auth.py
> +        to_encode = data.copy()
давай зробимо функцію для кода з create_access_token та create_refresh_token який має однакову логіку

2024-10-06 21:39 UTC, iamleeon commented on src/database/models.py
> +    username = Column(String(50), nullable=False, index=True)
Маєш на увазі зробити unique key для username чи для id також?

2024-10-06 21:56 UTC, iamleeon commented on src/services/auth.py
> +        to_encode = data.copy()
Хороша ідея!

2024-10-06 21:59 UTC, iamleeon commented on src/database/models.py
> +    username = Column(String(50), nullable=False, index=True)
А, id у нас primary_key, тому немає змісту робити його unique. Додаю unique=True для username.

2024-10-07 12:08 UTC, ValKurta approved these changes

2024-10-07 12:08 UTC, merged